# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l5Ktxt5JV7nxio8ycvAg8jpvcGe2uWZP
"""

import os
import torch
import pandas as pd
from transformers import AutoTokenizer, AutoModelForCausalLM
from sentence_transformers import SentenceTransformer, CrossEncoder

# ─── INLINE HELPERS (this file is self-contained, no hall_utils.py needed) ───
import re, csv, json

_MODELS    = r'BART|LED|PEGASUS|MISTRAL-7B|FALCON-7B'
_HALL_PAT  = re.compile(rf'^({_MODELS})(first|middle|last)(.+)$')
_STOPWORDS = {"the","and","that","this","with","from","were","have","has","had","was",
              "are","for","not","but","which","their","they","them","his","her","she",
              "him","who","whom","been","into","under","upon","such","shall","would",
              "could","there","these","those","than","then","also"}

def _load_hall_csv(path):
    rows = []
    with open(path, "r", encoding="utf-8-sig", newline="") as f:
        for row in csv.DictReader(f):
            sent = (row.get("sentence") or "").strip()
            if not sent:
                continue
            sid = (row.get("source_id") or "").strip()
            rows.append({"model": (row.get("model") or "").strip(),
                         "position": (row.get("position") or "").strip(),
                         "sentence": sent,
                         "source_id": sid if sid != "" else None,
                         "score": (row.get("score") or "").strip()})
    return rows

def load_hall_sentences(path):
    """Load hallucinated sentences. .csv -> labelled rows (with source_id);
    .txt -> legacy glued '<MODEL><position><sentence>' dump (source_id=None)."""
    if not os.path.exists(path):
        raise FileNotFoundError(f"{path} not found")
    if path.lower().endswith(".csv"):
        return _load_hall_csv(path)
    rows = []
    with open(path, "r", encoding="utf-8", errors="ignore") as f:
        for line in f:
            m = _HALL_PAT.match(line.strip())
            if m:
                rows.append({"model": m.group(1), "position": m.group(2),
                             "sentence": m.group(3).strip(), "source_id": None, "score": ""})
    return rows

def load_source_records(path):
    """Load the source judgments (the truth)."""
    if not os.path.exists(path):
        raise FileNotFoundError(f"{path} not found")
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    return data if isinstance(data, list) else [data]

def split_sentences(text):
    text = " ".join(str(text).split())
    parts = re.split(r'(?<=[.!?])\s+', text)
    return [s.strip() for s in parts if len(s.strip()) > 15]

def _keywords(text):
    return {w for w in re.findall(r'[A-Za-z]{4,}', text.lower()) if w not in _STOPWORDS}

def match_record(sentence, records):
    """Infer the source judgment by keyword overlap (fallback when no source_id)."""
    sw = _keywords(sentence)
    best_score, best_rec = -1, records[0]
    for rec in records:
        hay = (str(rec.get("judgment","")) + " " + str(rec.get("reference_summary",""))).lower()
        score = sum(1 for w in sw if w in hay)
        if score > best_score:
            best_score, best_rec = score, rec
    return best_rec

def pick_record(row, records):
    """Use the labelled source_id (exact lookup); else fall back to inference."""
    sid = row.get("source_id")
    if sid not in (None, ""):
        sid_str = str(sid).strip()
        for rec in records:
            if str(rec.get("id")).strip() == sid_str:
                return rec
        print(f"[WARN] source_id {sid_str!r} not found in test.json - inferring instead.")
    return match_record(row["sentence"], records)

def save_corrected(out_path, rows, extra_cols=None):
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    cols = ["model","position","source_id","original_sentence","corrected_sentence"] + list(extra_cols or [])
    with open(out_path, "w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=cols, extrasaction="ignore")
        w.writeheader()
        for r in rows:
            w.writerow(r)
    print(f"[SAVE] Wrote {len(rows)} corrected sentences -> {out_path}")
def save_mitigated(out_path, rows):
    """Write ONLY the mitigated sentences in the SAME schema as hall_sent_clean.csv
    (source_id, model, position, score, sentence) so this file can be re-fed to the
    detection methods and compared against the original input. score is left blank."""
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    with open(out_path, "w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=["source_id","model","position","sentence"])
        w.writeheader()
        for r in rows:
            w.writerow({"source_id": r.get("source_id",""),
                        "model":     r.get("model",""),
                        "position":  r.get("position",""),
                        "sentence":  r.get("corrected_sentence","")})
    print(f"[SAVE] Wrote {len(rows)} mitigated sentences -> {out_path}")
# ─── END INLINE HELPERS ─────────────────────────────────────────────────────

# ─── PICK YOUR CORRECTOR MODEL ───────────────────────────────────────────────
MODEL_ENGINE = "mistral"          # "mistral"  or  "falcon"

MODEL_IDS = {
    "mistral": "mistralai/Mistral-7B-Instruct-v0.2"
}
assert MODEL_ENGINE in MODEL_IDS, f"MODEL_ENGINE must be one of {list(MODEL_IDS)}"
MODEL_ID = MODEL_IDS[MODEL_ENGINE]

# ─── CONFIGURATION ───────────────────────────────────────────────────────────
EMBED_MODEL = "all-MiniLM-L6-v2"
NLI_MODEL   = "cross-encoder/nli-deberta-v3-small"
HALL_PATH   = "/content/hall_sent_clean.csv"
SRC_PATH    = "/content/test.json"
OUT_PATH    = f"outputs/role_part_{MODEL_ENGINE}_mitigated.csv"
MAX_CTX     = 4096 if MODEL_ENGINE == "mistral" else 2048
DEVICE      = "cuda" if torch.cuda.is_available() else "cpu"

# ─── POSITIONAL CONSTRAINT TABLE ─────────────────────────────────────────────
# position label comes directly from hall_sent_clean.csv
# no judgment splitting needed — position is already known
POSITION_CONFIG = {
    "first": {
        "top_k":        2,
        "temperature":  0.3,
        "nli_check":    False,
        "nli_threshold":None,
        "max_retries":  0,
        "fallback":     False,
    },
    "middle": {
        "top_k":        3,
        "temperature":  0.2,
        "nli_check":    True,
        "nli_threshold":0.40,
        "max_retries":  2,
        "fallback":     False,
    },
    "last": {
        "top_k":        4,
        "temperature":  0.1,
        "nli_check":    True,
        "nli_threshold":0.50,
        "max_retries":  3,
        "fallback":     True,
    }
}

# ─── PROMPT BUILDER ──────────────────────────────────────────────────────────
def build_prompt(position, context, sentence):
    POSITION_INSTRUCTION = {
        "first": (
            "You are correcting the OPENING sentence of a legal-case summary. "
            "Lightly rewrite it to remove any unsupported claims. "
            "Use ONLY the context provided."
        ),
        "middle": (
            "You are correcting a MIDDLE sentence of a legal-case summary. "
            "Middle sentences often contain fabricated dates, section numbers, "
            "or party names. Rewrite strictly using ONLY the context. "
            "Drop or fix every claim not found in the context."
        ),
        "last": (
            "You are correcting the FINAL sentence of a legal-case summary. "
            "Final sentences have the highest hallucination — they often invent "
            "conclusions. Be extremely strict: use ONLY what is explicitly in "
            "the context. Remove any claim that cannot be verified. "
            "Reply with one corrected sentence only."
        ),
    }
    instruction = POSITION_INSTRUCTION[position]
    if MODEL_ENGINE == "mistral":
        return (
            f"<s>[INST] {instruction}\n\n"
            f"Context:\n{context}\n\n"
            f"Sentence: {sentence} [/INST]"
        )
    return (
        f"{instruction}\n\n"
        f"Context:\n{context}\n\n"
        f"Sentence: {sentence}\n\n"
        f"Corrected sentence:"
    )

# ─── 1. LOAD DATA ────────────────────────────────────────────────────────────
os.makedirs("outputs", exist_ok=True)

# These are your real inputs — they must exist (no dummy data is created).
if not os.path.exists(HALL_PATH):
    raise FileNotFoundError(
        f"{HALL_PATH} not found. Put your cleaned hallucinated-sentence file there "
        f"with columns: source_id, model, position, score, sentence."
    )
if not os.path.exists(SRC_PATH):
    raise FileNotFoundError(f"{SRC_PATH} not found (the source judgments / test.json).")

print(f"[1/4] Engine={MODEL_ENGINE} | loading {HALL_PATH} and {SRC_PATH} ...")
hall_rows = load_hall_sentences(HALL_PATH)
records   = load_source_records(SRC_PATH)
print(f"      {len(hall_rows)} hallucinated sentences | {len(records)} source judgments")
print(f"      position labels read directly from CSV — no judgment splitting needed")

# ─── 2. LOAD MODELS ──────────────────────────────────────────────────────────
print(f"[2/4] Loading embedder + NLI + {MODEL_ID} on {DEVICE} ...")
embedder  = SentenceTransformer(EMBED_MODEL, device=DEVICE)

# NLI label order: [contradiction=0, entailment=1, neutral=2]
nli = CrossEncoder(NLI_MODEL, device=DEVICE)

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
tokenizer.pad_token = tokenizer.eos_token
model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    torch_dtype=torch.float16 if DEVICE == "cuda" else torch.float32,
    device_map="auto" if DEVICE == "cuda" else None,
    low_cpu_mem_usage=True,
)
model.eval()

# ─── 3. HELPER FUNCTIONS ─────────────────────────────────────────────────────

# Evidence cache — avoid re-encoding same judgment twice
_pool_cache = {}

def retrieve_evidence(query, record, k):
    """
    Retrieve top-k sentences from the FULL source judgment.
    Position is already known from the CSV — no need to split judgment.
    top_k varies by position (2 / 3 / 4) to apply positional constraint.
    """
    sid = record.get("id")
    if sid not in _pool_cache:
        pool = split_sentences(record.get("judgment", "")) or [record.get("judgment", "")]
        emb  = embedder.encode(
            pool, convert_to_numpy=True, normalize_embeddings=True
        )
        _pool_cache[sid] = (pool, emb)
    pool, emb = _pool_cache[sid]
    q   = embedder.encode([query], convert_to_numpy=True, normalize_embeddings=True)[0]
    idx = (emb @ q).argsort()[::-1][:k]
    return [pool[i] for i in idx]


def nli_entailment(premise, hypothesis):
    """Entailment probability from DeBERTa NLI. Index 1 = entailment."""
    scores = nli.predict([(premise, hypothesis)], apply_softmax=True)
    return round(float(scores[0][1]), 4)


def generate_once(position, context_str, sentence, temperature):
    """Single generation pass at given temperature."""
    prompt = build_prompt(position, context_str, sentence)
    inputs = tokenizer(
        prompt, return_tensors="pt",
        truncation=True, max_length=MAX_CTX
    ).to(model.device)

    with torch.no_grad():
        out = model.generate(
            **inputs,
            max_new_tokens=120,
            do_sample=True,
            temperature=temperature,
            top_p=0.9,
            repetition_penalty=1.15,
            use_cache=True,
            pad_token_id=tokenizer.eos_token_id,
        )
    raw = tokenizer.decode(
        out[0][inputs["input_ids"].shape[1]:],
        skip_special_tokens=True
    ).strip().strip('"')

    # Strip prompt artifacts
    for prefix in ["Corrected sentence:", "Corrected:", "Answer:"]:
        if raw.lower().startswith(prefix.lower()):
            raw = raw[len(prefix):].strip()

    # First sentence only
    parts = [s.strip() for s in raw.split(".") if s.strip()]
    return (parts[0] + ".") if parts else raw


def correct_with_constraint(position, sentence, evidence):
    """
    Apply position-specific constraint.
    Position label comes from the CSV — already known.

    first  → single pass, no NLI check needed
    middle → single pass + NLI verify, retry up to 2x
    last   → single pass + NLI verify, retry up to 3x, fallback if all fail
    """
    cfg          = POSITION_CONFIG[position]
    temperature  = cfg["temperature"]
    nli_check    = cfg["nli_check"]
    threshold    = cfg["nli_threshold"]
    max_retries  = cfg["max_retries"]
    use_fallback = cfg["fallback"]

    context_str = "\n".join(f"- {e}" for e in evidence)
    premise     = " ".join(evidence)

    # first — no NLI verification
    if not nli_check:
        fixed = generate_once(position, context_str, sentence, temperature)
        score = nli_entailment(premise, fixed)
        return fixed, score, 0, "no_check"

    # middle / last — generate then verify
    fixed = generate_once(position, context_str, sentence, temperature)
    score = nli_entailment(premise, fixed)

    if score >= threshold:
        return fixed, score, 0, "passed_first_try"

    # retry loop — reduce temperature by 0.05 each attempt
    for attempt in range(1, max_retries + 1):
        retry_temp = max(temperature - 0.05 * attempt, 0.05)
        fixed      = generate_once(position, context_str, sentence, retry_temp)
        score      = nli_entailment(premise, fixed)
        if score >= threshold:
            return fixed, score, attempt, f"passed_retry_{attempt}"

    # fallback for last position only
    if use_fallback:
        fallback = "This claim could not be verified against the source judgment."
        fb_score = nli_entailment(premise, fallback)
        return fallback, fb_score, max_retries, "fallback"

    # middle: return best attempt even if below threshold
    return fixed, score, max_retries, "below_threshold_accepted"


# ─── 4. MAIN LOOP ────────────────────────────────────────────────────────────
print("[3/4] Correcting with positional constraint ...\n")
print("      Position label read from CSV — no judgment splitting")
print("      first  → temp=0.3 top_k=2 no NLI")
print("      middle → temp=0.2 top_k=3 NLI≥0.40 retry×2")
print("      last   → temp=0.1 top_k=4 NLI≥0.50 retry×3 fallback\n")

results = []

for i, r in enumerate(hall_rows, 1):
    # position comes directly from hall_sent_clean.csv
    # this is the ONLY source of position — no re-splitting needed
    position = r["position"]
    sentence = r["sentence"]
    cfg      = POSITION_CONFIG[position]

    # resolve source judgment
    rec = pick_record(r, records)

    # retrieve from FULL judgment with position-specific top_k
    evidence = retrieve_evidence(sentence, rec, k=cfg["top_k"])

    # apply positional constraint correction
    fixed, score, retries, outcome = correct_with_constraint(
        position, sentence, evidence
    )

    # score original for comparison
    premise        = " ".join(evidence)
    original_score = nli_entailment(premise, sentence)
    is_mitigated   = (score > original_score and
                      score >= (cfg["nli_threshold"] or 0.0))

    flag = "✓ MITIGATED" if is_mitigated else "✗ WEAK"
    print(f"[{i}/{len(hall_rows)}] {r['model']}/{position} "
          f"(src {rec.get('id')}) | {flag}")
    print(f"   position from CSV : {position}")
    print(f"   constraint applied: temp={cfg['temperature']} "
          f"top_k={cfg['top_k']} nli_check={cfg['nli_check']}")
    print(f"   orig score : {original_score}")
    print(f"   corr score : {score}  retries={retries}  outcome={outcome}")
    print(f"   ORIG  : {sentence}")
    print(f"   FIXED : {fixed}\n")

    results.append({
        "model":             r["model"],
        "position":          position,
        "source_id":         rec.get("id"),
        "original_sentence": sentence,
        "corrected_sentence":fixed,
        "role":              position,
        "constraint_temp":   cfg["temperature"],
        "constraint_topk":   cfg["top_k"],
        "nli_check":         cfg["nli_check"],
        "original_score":    original_score,
        "corrected_score":   score,
        "retries":           retries,
        "outcome":           outcome,
        "is_mitigated":      is_mitigated,
    })

# ─── 5. SUMMARY + SAVE ───────────────────────────────────────────────────────
print("[4/4] Summary\n")
print("=" * 70)

df = pd.DataFrame(results)

summary = (
    df.groupby("position")
    .agg(
        total=("is_mitigated", "count"),
        mitigated=("is_mitigated", lambda x: int(x.sum())),
        avg_orig_score=("original_score", "mean"),
        avg_corr_score=("corrected_score", "mean"),
        avg_retries=("retries", "mean"),
    )
    .reindex(["first", "middle", "last"])
    .round(4)
)
print("By position (first < middle < last constraint ordering):")
print(summary.to_string())

print("\nBy model:")
print(
    df.groupby("model")
    .agg(
        total=("is_mitigated", "count"),
        mitigated=("is_mitigated", lambda x: int(x.sum())),
        avg_corr_score=("corrected_score", "mean"),
    )
    .round(4)
    .to_string()
)

save_mitigated(OUT_PATH, results)
print(f"\nSaved: {OUT_PATH}")
print("DONE\n")

import os
import torch
import pandas as pd
from transformers import AutoTokenizer, AutoModelForCausalLM
from sentence_transformers import SentenceTransformer, CrossEncoder

# ─── INLINE HELPERS (this file is self-contained, no hall_utils.py needed) ───
import re, csv, json

_MODELS    = r'BART|LED|PEGASUS|MISTRAL-7B|FALCON-7B'
_HALL_PAT  = re.compile(rf'^({_MODELS})(first|middle|last)(.+)$')
_STOPWORDS = {"the","and","that","this","with","from","were","have","has","had","was",
              "are","for","not","but","which","their","they","them","his","her","she",
              "him","who","whom","been","into","under","upon","such","shall","would",
              "could","there","these","those","than","then","also"}

def _load_hall_csv(path):
    rows = []
    with open(path, "r", encoding="utf-8-sig", newline="") as f:
        for row in csv.DictReader(f):
            sent = (row.get("sentence") or "").strip()
            if not sent:
                continue
            sid = (row.get("source_id") or "").strip()
            rows.append({"model": (row.get("model") or "").strip(),
                         "position": (row.get("position") or "").strip(),
                         "sentence": sent,
                         "source_id": sid if sid != "" else None,
                         "score": (row.get("score") or "").strip()})
    return rows

def load_hall_sentences(path):
    """Load hallucinated sentences. .csv -> labelled rows (with source_id);
    .txt -> legacy glued '<MODEL><position><sentence>' dump (source_id=None)."""
    if not os.path.exists(path):
        raise FileNotFoundError(f"{path} not found")
    if path.lower().endswith(".csv"):
        return _load_hall_csv(path)
    rows = []
    with open(path, "r", encoding="utf-8", errors="ignore") as f:
        for line in f:
            m = _HALL_PAT.match(line.strip())
            if m:
                rows.append({"model": m.group(1), "position": m.group(2),
                             "sentence": m.group(3).strip(), "source_id": None, "score": ""})
    return rows

def load_source_records(path):
    """Load the source judgments (the truth)."""
    if not os.path.exists(path):
        raise FileNotFoundError(f"{path} not found")
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    return data if isinstance(data, list) else [data]

def split_sentences(text):
    text = " ".join(str(text).split())
    parts = re.split(r'(?<=[.!?])\s+', text)
    return [s.strip() for s in parts if len(s.strip()) > 15]

def _keywords(text):
    return {w for w in re.findall(r'[A-Za-z]{4,}', text.lower()) if w not in _STOPWORDS}

def match_record(sentence, records):
    """Infer the source judgment by keyword overlap (fallback when no source_id)."""
    sw = _keywords(sentence)
    best_score, best_rec = -1, records[0]
    for rec in records:
        hay = (str(rec.get("judgment","")) + " " + str(rec.get("reference_summary",""))).lower()
        score = sum(1 for w in sw if w in hay)
        if score > best_score:
            best_score, best_rec = score, rec
    return best_rec

def pick_record(row, records):
    """Use the labelled source_id (exact lookup); else fall back to inference."""
    sid = row.get("source_id")
    if sid not in (None, ""):
        sid_str = str(sid).strip()
        for rec in records:
            if str(rec.get("id")).strip() == sid_str:
                return rec
        print(f"[WARN] source_id {sid_str!r} not found in test.json - inferring instead.")
    return match_record(row["sentence"], records)

def save_corrected(out_path, rows, extra_cols=None):
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    cols = ["model","position","source_id","original_sentence","corrected_sentence"] + list(extra_cols or [])
    with open(out_path, "w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=cols, extrasaction="ignore")
        w.writeheader()
        for r in rows:
            w.writerow(r)
    print(f"[SAVE] Wrote {len(rows)} corrected sentences -> {out_path}")
def save_mitigated(out_path, rows):
    """Write ONLY the mitigated sentences in the SAME schema as hall_sent_clean.csv
    (source_id, model, position, score, sentence) so this file can be re-fed to the
    detection methods and compared against the original input. score is left blank."""
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    with open(out_path, "w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=["source_id","model","position","sentence"])
        w.writeheader()
        for r in rows:
            w.writerow({"source_id": r.get("source_id",""),
                        "model":     r.get("model",""),
                        "position":  r.get("position",""),
                        "sentence":  r.get("corrected_sentence","")})
    print(f"[SAVE] Wrote {len(rows)} mitigated sentences -> {out_path}")
# ─── END INLINE HELPERS ─────────────────────────────────────────────────────

# ─── PICK YOUR CORRECTOR MODEL ───────────────────────────────────────────────
MODEL_ENGINE = "falcon"          # "mistral"  or  "falcon"

MODEL_IDS = {
    #"mistral": "mistralai/Mistral-7B-Instruct-v0.2",
    "falcon":  "tiiuae/falcon-7b-instruct",
}
assert MODEL_ENGINE in MODEL_IDS, f"MODEL_ENGINE must be one of {list(MODEL_IDS)}"
MODEL_ID = MODEL_IDS[MODEL_ENGINE]

# ─── CONFIGURATION ───────────────────────────────────────────────────────────
EMBED_MODEL = "all-MiniLM-L6-v2"
NLI_MODEL   = "cross-encoder/nli-deberta-v3-small"
HALL_PATH   = "/content/hall_sent_clean.csv"
SRC_PATH    = "/content/test.json"
OUT_PATH    = f"outputs/role_part_{MODEL_ENGINE}_mitigated.csv"
MAX_CTX     = 4096 if MODEL_ENGINE == "mistral" else 2048
DEVICE      = "cuda" if torch.cuda.is_available() else "cpu"

# ─── POSITIONAL CONSTRAINT TABLE ─────────────────────────────────────────────
# position label comes directly from hall_sent_clean.csv
# no judgment splitting needed — position is already known
POSITION_CONFIG = {
    "first": {
        "top_k":        2,
        "temperature":  0.3,
        "nli_check":    False,
        "nli_threshold":None,
        "max_retries":  0,
        "fallback":     False,
    },
    "middle": {
        "top_k":        3,
        "temperature":  0.2,
        "nli_check":    True,
        "nli_threshold":0.40,
        "max_retries":  2,
        "fallback":     False,
    },
    "last": {
        "top_k":        4,
        "temperature":  0.1,
        "nli_check":    True,
        "nli_threshold":0.50,
        "max_retries":  3,
        "fallback":     True,
    },
}

# ─── PROMPT BUILDER ──────────────────────────────────────────────────────────
def build_prompt(position, context, sentence):
    POSITION_INSTRUCTION = {
        "first": (
            "You are correcting the OPENING sentence of a legal-case summary. "
            "Lightly rewrite it to remove any unsupported claims. "
            "Use ONLY the context provided."
        ),
        "middle": (
            "You are correcting a MIDDLE sentence of a legal-case summary. "
            "Middle sentences often contain fabricated dates, section numbers, "
            "or party names. Rewrite strictly using ONLY the context. "
            "Drop or fix every claim not found in the context."
        ),
        "last": (
            "You are correcting the FINAL sentence of a legal-case summary. "
            "Final sentences have the highest hallucination — they often invent "
            "conclusions. Be extremely strict: use ONLY what is explicitly in "
            "the context. Remove any claim that cannot be verified. "
            "Reply with one corrected sentence only."
        ),
    }
    instruction = POSITION_INSTRUCTION[position]
    if MODEL_ENGINE == "mistral":
        return (
            f"<s>[INST] {instruction}\n\n"
            f"Context:\n{context}\n\n"
            f"Sentence: {sentence} [/INST]"
        )
    return (
        f"{instruction}\n\n"
        f"Context:\n{context}\n\n"
        f"Sentence: {sentence}\n\n"
        f"Corrected sentence:"
    )

# ─── 1. LOAD DATA ────────────────────────────────────────────────────────────
os.makedirs("outputs", exist_ok=True)

# These are your real inputs — they must exist (no dummy data is created).
if not os.path.exists(HALL_PATH):
    raise FileNotFoundError(
        f"{HALL_PATH} not found. Put your cleaned hallucinated-sentence file there "
        f"with columns: source_id, model, position, score, sentence."
    )
if not os.path.exists(SRC_PATH):
    raise FileNotFoundError(f"{SRC_PATH} not found (the source judgments / test.json).")

print(f"[1/4] Engine={MODEL_ENGINE} | loading {HALL_PATH} and {SRC_PATH} ...")
hall_rows = load_hall_sentences(HALL_PATH)
records   = load_source_records(SRC_PATH)
print(f"      {len(hall_rows)} hallucinated sentences | {len(records)} source judgments")
print(f"      position labels read directly from CSV — no judgment splitting needed")

# ─── 2. LOAD MODELS ──────────────────────────────────────────────────────────
print(f"[2/4] Loading embedder + NLI + {MODEL_ID} on {DEVICE} ...")
embedder  = SentenceTransformer(EMBED_MODEL, device=DEVICE)

# NLI label order: [contradiction=0, entailment=1, neutral=2]
nli = CrossEncoder(NLI_MODEL, device=DEVICE)

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
tokenizer.pad_token = tokenizer.eos_token
model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    torch_dtype=torch.float16 if DEVICE == "cuda" else torch.float32,
    device_map="auto" if DEVICE == "cuda" else None,
    low_cpu_mem_usage=True,
)
model.eval()

# ─── 3. HELPER FUNCTIONS ─────────────────────────────────────────────────────

# Evidence cache — avoid re-encoding same judgment twice
_pool_cache = {}

def retrieve_evidence(query, record, k):
    """
    Retrieve top-k sentences from the FULL source judgment.
    Position is already known from the CSV — no need to split judgment.
    top_k varies by position (2 / 3 / 4) to apply positional constraint.
    """
    sid = record.get("id")
    if sid not in _pool_cache:
        pool = split_sentences(record.get("judgment", "")) or [record.get("judgment", "")]
        emb  = embedder.encode(
            pool, convert_to_numpy=True, normalize_embeddings=True
        )
        _pool_cache[sid] = (pool, emb)
    pool, emb = _pool_cache[sid]
    q   = embedder.encode([query], convert_to_numpy=True, normalize_embeddings=True)[0]
    idx = (emb @ q).argsort()[::-1][:k]
    return [pool[i] for i in idx]


def nli_entailment(premise, hypothesis):
    """Entailment probability from DeBERTa NLI. Index 1 = entailment."""
    scores = nli.predict([(premise, hypothesis)], apply_softmax=True)
    return round(float(scores[0][1]), 4)


def generate_once(position, context_str, sentence, temperature):
    """Single generation pass at given temperature."""
    prompt = build_prompt(position, context_str, sentence)
    inputs = tokenizer(
        prompt, return_tensors="pt",
        truncation=True, max_length=MAX_CTX
    ).to(model.device)

    with torch.no_grad():
        out = model.generate(
            **inputs,
            max_new_tokens=120,
            do_sample=True,
            temperature=temperature,
            top_p=0.9,
            repetition_penalty=1.15,
            use_cache=True,
            pad_token_id=tokenizer.eos_token_id,
        )
    raw = tokenizer.decode(
        out[0][inputs["input_ids"].shape[1]:],
        skip_special_tokens=True
    ).strip().strip('"')

    # Strip prompt artifacts
    for prefix in ["Corrected sentence:", "Corrected:", "Answer:"]:
        if raw.lower().startswith(prefix.lower()):
            raw = raw[len(prefix):].strip()

    # First sentence only
    parts = [s.strip() for s in raw.split(".") if s.strip()]
    return (parts[0] + ".") if parts else raw


def correct_with_constraint(position, sentence, evidence):
    """
    Apply position-specific constraint.
    Position label comes from the CSV — already known.

    first  → single pass, no NLI check needed
    middle → single pass + NLI verify, retry up to 2x
    last   → single pass + NLI verify, retry up to 3x, fallback if all fail
    """
    cfg          = POSITION_CONFIG[position]
    temperature  = cfg["temperature"]
    nli_check    = cfg["nli_check"]
    threshold    = cfg["nli_threshold"]
    max_retries  = cfg["max_retries"]
    use_fallback = cfg["fallback"]

    context_str = "\n".join(f"- {e}" for e in evidence)
    premise     = " ".join(evidence)

    # first — no NLI verification
    if not nli_check:
        fixed = generate_once(position, context_str, sentence, temperature)
        score = nli_entailment(premise, fixed)
        return fixed, score, 0, "no_check"

    # middle / last — generate then verify
    fixed = generate_once(position, context_str, sentence, temperature)
    score = nli_entailment(premise, fixed)

    if score >= threshold:
        return fixed, score, 0, "passed_first_try"

    # retry loop — reduce temperature by 0.05 each attempt
    for attempt in range(1, max_retries + 1):
        retry_temp = max(temperature - 0.05 * attempt, 0.05)
        fixed      = generate_once(position, context_str, sentence, retry_temp)
        score      = nli_entailment(premise, fixed)
        if score >= threshold:
            return fixed, score, attempt, f"passed_retry_{attempt}"

    # fallback for last position only
    if use_fallback:
        fallback = "This claim could not be verified against the source judgment."
        fb_score = nli_entailment(premise, fallback)
        return fallback, fb_score, max_retries, "fallback"

    # middle: return best attempt even if below threshold
    return fixed, score, max_retries, "below_threshold_accepted"


# ─── 4. MAIN LOOP ────────────────────────────────────────────────────────────
print("[3/4] Correcting with positional constraint ...\n")
print("      Position label read from CSV — no judgment splitting")
print("      first  → temp=0.3 top_k=2 no NLI")
print("      middle → temp=0.2 top_k=3 NLI≥0.40 retry×2")
print("      last   → temp=0.1 top_k=4 NLI≥0.50 retry×3 fallback\n")

results = []

for i, r in enumerate(hall_rows, 1):
    # position comes directly from hall_sent_clean.csv
    # this is the ONLY source of position — no re-splitting needed
    position = r["position"]
    sentence = r["sentence"]
    cfg      = POSITION_CONFIG[position]

    # resolve source judgment
    rec = pick_record(r, records)

    # retrieve from FULL judgment with position-specific top_k
    evidence = retrieve_evidence(sentence, rec, k=cfg["top_k"])

    # apply positional constraint correction
    fixed, score, retries, outcome = correct_with_constraint(
        position, sentence, evidence
    )

    # score original for comparison
    premise        = " ".join(evidence)
    original_score = nli_entailment(premise, sentence)
    is_mitigated   = (score > original_score and
                      score >= (cfg["nli_threshold"] or 0.0))

    flag = "✓ MITIGATED" if is_mitigated else "✗ WEAK"
    print(f"[{i}/{len(hall_rows)}] {r['model']}/{position} "
          f"(src {rec.get('id')}) | {flag}")
    print(f"   position from CSV : {position}")
    print(f"   constraint applied: temp={cfg['temperature']} "
          f"top_k={cfg['top_k']} nli_check={cfg['nli_check']}")
    print(f"   orig score : {original_score}")
    print(f"   corr score : {score}  retries={retries}  outcome={outcome}")
    print(f"   ORIG  : {sentence}")
    print(f"   FIXED : {fixed}\n")

    results.append({
        "model":             r["model"],
        "position":          position,
        "source_id":         rec.get("id"),
        "original_sentence": sentence,
        "corrected_sentence":fixed,
        "role":              position,
        "constraint_temp":   cfg["temperature"],
        "constraint_topk":   cfg["top_k"],
        "nli_check":         cfg["nli_check"],
        "original_score":    original_score,
        "corrected_score":   score,
        "retries":           retries,
        "outcome":           outcome,
        "is_mitigated":      is_mitigated,
    })

# ─── 5. SUMMARY + SAVE ───────────────────────────────────────────────────────
print("[4/4] Summary\n")
print("=" * 70)

df = pd.DataFrame(results)

summary = (
    df.groupby("position")
    .agg(
        total=("is_mitigated", "count"),
        mitigated=("is_mitigated", lambda x: int(x.sum())),
        avg_orig_score=("original_score", "mean"),
        avg_corr_score=("corrected_score", "mean"),
        avg_retries=("retries", "mean"),
    )
    .reindex(["first", "middle", "last"])
    .round(4)
)
print("By position (first < middle < last constraint ordering):")
print(summary.to_string())

print("\nBy model:")
print(
    df.groupby("model")
    .agg(
        total=("is_mitigated", "count"),
        mitigated=("is_mitigated", lambda x: int(x.sum())),
        avg_corr_score=("corrected_score", "mean"),
    )
    .round(4)
    .to_string()
)

save_mitigated(OUT_PATH, results)
print(f"\nSaved: {OUT_PATH}")
print("DONE\n")

