# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12glu7_tk8CY_i09pkjIS-lYqxerNORRP
"""

"""
Mitigation = BASIC RAG.   Corrector model is switchable (Mistral or Falcon).

For every hallucinated sentence in hall_sent_clean.csv:
  1. resolve its source judgment in test.json (via labelled source_id),
  2. retrieve the top-k most relevant evidence sentences from that judgment,
  3. ask the corrector LLM to rewrite the sentence so it is faithful to evidence.
Output: outputs/basic_rag_<engine>_mitigated.csv  (original vs corrected).

>>> Pick the corrector model by editing MODEL_ENGINE below. <<<
"""

import numpy as np
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
from sentence_transformers import SentenceTransformer

# ─── INLINE HELPERS (this file is self-contained, no hall_utils.py needed) ───
import os, re, csv, json

_MODELS    = r'MISTRAL-7B|FALCON-7B'
_HALL_PAT  = re.compile(rf'^({_MODELS})(first|middle|last)(.+)$')
_STOPWORDS = {"the","and","that","this","with","from","were","have","has","had","was",
              "are","for","not","but","which","their","they","them","his","her","she",
              "him","who","whom","been","into","under","upon","such","shall","would",
              "could","there","these","those","than","then","also"}

def _load_hall_csv(path):
    rows = []
    with open(path, "r", encoding="utf-8-sig", newline="") as f:
        for row in csv.DictReader(f):
            sent = (row.get("sentence") or "").strip()
            if not sent:
                continue
            sid = (row.get("source_id") or "").strip()
            rows.append({"model": (row.get("model") or "").strip(),
                         "position": (row.get("position") or "").strip(),
                         "sentence": sent,
                         "source_id": sid if sid != "" else None,
                         "score": (row.get("score") or "").strip()})
    return rows

def load_hall_sentences(path):
    """Load hallucinated sentences. .csv -> labelled rows (with source_id);
    .txt -> legacy glued '<MODEL><position><sentence>' dump (source_id=None)."""
    if not os.path.exists(path):
        raise FileNotFoundError(f"{path} not found")
    if path.lower().endswith(".csv"):
        return _load_hall_csv(path)
    rows = []
    with open(path, "r", encoding="utf-8", errors="ignore") as f:
        for line in f:
            m = _HALL_PAT.match(line.strip())
            if m:
                rows.append({"model": m.group(1), "position": m.group(2),
                             "sentence": m.group(3).strip(), "source_id": None, "score": ""})
    return rows

def load_source_records(path):
    """Load the source judgments (the truth)."""
    if not os.path.exists(path):
        raise FileNotFoundError(f"{path} not found")
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    return data if isinstance(data, list) else [data]

def split_sentences(text):
    text = " ".join(str(text).split())
    parts = re.split(r'(?<=[.!?])\s+', text)
    return [s.strip() for s in parts if len(s.strip()) > 15]

def _keywords(text):
    return {w for w in re.findall(r'[A-Za-z]{4,}', text.lower()) if w not in _STOPWORDS}

def match_record(sentence, records):
    """Infer the source judgment by keyword overlap (fallback when no source_id)."""
    sw = _keywords(sentence)
    best_score, best_rec = -1, records[0]
    for rec in records:
        hay = (str(rec.get("judgment","")) + " " + str(rec.get("reference_summary",""))).lower()
        score = sum(1 for w in sw if w in hay)
        if score > best_score:
            best_score, best_rec = score, rec
    return best_rec

def pick_record(row, records):
    """Use the labelled source_id (exact lookup); else fall back to inference."""
    sid = row.get("source_id")
    if sid not in (None, ""):
        sid_str = str(sid).strip()
        for rec in records:
            if str(rec.get("id")).strip() == sid_str:
                return rec
        print(f"[WARN] source_id {sid_str!r} not found in test.json - inferring instead.")
    return match_record(row["sentence"], records)

def save_corrected(out_path, rows, extra_cols=None):
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    cols = ["model","position","source_id","original_sentence","corrected_sentence"] + list(extra_cols or [])
    with open(out_path, "w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=cols, extrasaction="ignore")
        w.writeheader()
        for r in rows:
            w.writerow(r)
    print(f"[SAVE] Wrote {len(rows)} corrected sentences -> {out_path}")
def save_mitigated(out_path, rows):
    """Write ONLY the mitigated sentences in the SAME schema as hall_sent_clean.csv
    (source_id, model, position, score, sentence) so this file can be re-fed to the
    detection methods and compared against the original input. score is left blank."""
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    with open(out_path, "w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=["source_id","model","position","sentence"])
        w.writeheader()
        for r in rows:
            w.writerow({"source_id": r.get("source_id",""),
                        "model":     r.get("model",""),
                        "position":  r.get("position",""),
                        "sentence":  r.get("corrected_sentence","")})
    print(f"[SAVE] Wrote {len(rows)} mitigated sentences -> {out_path}")
# ─── END INLINE HELPERS ─────────────────────────────────────────────────────

# ─── PICK YOUR CORRECTOR MODEL ──────────────────────────────────────────────
MODEL_ENGINE = "mistral"          # "mistral"  or  "falcon"

MODEL_IDS = {
    "mistral": "mistralai/Mistral-7B-Instruct-v0.2",
    #"falcon":  "tiiuae/falcon-7b-instruct",
}
assert MODEL_ENGINE in MODEL_IDS, f"MODEL_ENGINE must be one of {list(MODEL_IDS)}"
MODEL_ID = MODEL_IDS[MODEL_ENGINE]

# ─── CONFIGURATION ──────────────────────────────────────────────────────────
EMBED_MODEL = "all-MiniLM-L6-v2"
HALL_PATH   = "/content/hall_sent_clean.csv"
SRC_PATH    = "/content/test.json"
OUT_PATH    = f"outputs/basic_rag_{MODEL_ENGINE}_mitigated.csv"
TOP_K       = 3 if MODEL_ENGINE == "mistral" else 2     # Falcon has a 2048 window
MAX_CTX     = 4096 if MODEL_ENGINE == "mistral" else 2048
GEN_TEMP    = 0.1 if MODEL_ENGINE == "mistral" else 0.2
DEVICE      = "cuda" if torch.cuda.is_available() else "cpu"

INSTRUCTION = ("You are correcting a sentence from a legal-case summary so it is faithful "
               "to the source judgment. Use ONLY the context below. Rewrite the sentence to "
               "be factually accurate; drop or fix any claim not supported by the context. "
               "Reply with the corrected sentence only.")

def build_prompt(context, sentence):
    """Engine-specific instruction wrapper."""
    if MODEL_ENGINE == "mistral":
        return f"<s>[INST] {INSTRUCTION}\n\nContext:\n{context}\n\nSentence to correct: {sentence} [/INST]"
    return (f"{INSTRUCTION}\n\nContext:\n{context}\n\n"
            f"Sentence to correct: {sentence}\n\nCorrected sentence:")

# ─── 1. LOAD TARGETS (hallucinated) + TRUTH (source judgments) ──────────────
print(f"[1/4] Engine={MODEL_ENGINE} | loading {HALL_PATH} and {SRC_PATH} ...")
hall_rows = load_hall_sentences(HALL_PATH)
records   = load_source_records(SRC_PATH)
print(f"      {len(hall_rows)} hallucinated sentences | {len(records)} source judgments")

# ─── 2. EMBEDDER + EVIDENCE RETRIEVAL ───────────────────────────────────────
print("[2/4] Loading embedder ...")
embedder = SentenceTransformer(EMBED_MODEL, device=DEVICE)
_pool_cache = {}

def retrieve_evidence(query, record, k=TOP_K):
    sid = record.get("id")
    if sid not in _pool_cache:
        pool = split_sentences(record.get("judgment", "")) or [record.get("judgment", "")]
        emb  = embedder.encode(pool, convert_to_numpy=True, normalize_embeddings=True)
        _pool_cache[sid] = (pool, emb)
    pool, emb = _pool_cache[sid]
    q = embedder.encode([query], convert_to_numpy=True, normalize_embeddings=True)[0]
    idx = (emb @ q).argsort()[::-1][:k]
    return [pool[i] for i in idx]

# ─── 3. LOAD CORRECTOR LLM ──────────────────────────────────────────────────
print(f"[3/4] Loading {MODEL_ID} on {DEVICE} ...")
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
tokenizer.pad_token = tokenizer.eos_token
model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    torch_dtype=torch.float16 if DEVICE == "cuda" else torch.float32,
    device_map="auto" if DEVICE == "cuda" else None,
    low_cpu_mem_usage=True,
)

def correct_sentence(bad_sentence, evidence):
    context = "\n".join(f"- {e}" for e in evidence)
    prompt  = build_prompt(context, bad_sentence)
    inputs  = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=MAX_CTX).to(model.device)
    with torch.no_grad():
        out = model.generate(**inputs, max_new_tokens=120, do_sample=True, temperature=GEN_TEMP,
                             top_p=0.9, pad_token_id=tokenizer.eos_token_id)
    text = tokenizer.decode(out[0][inputs["input_ids"].shape[1]:], skip_special_tokens=True)
    return text.strip().strip('"')

# ─── 4. CORRECT EACH HALLUCINATED SENTENCE ──────────────────────────────────
print("[4/4] Correcting sentences ...\n")
results = []
for i, r in enumerate(hall_rows, 1):
    rec      = pick_record(r, records)
    evidence = retrieve_evidence(r["sentence"], rec, k=TOP_K)
    fixed    = correct_sentence(r["sentence"], evidence)
    print(f"[{i}/{len(hall_rows)}] {r['model']}/{r['position']}  (source id {rec.get('id')})")
    print(f"   ORIG : {r['sentence']}")
    print(f"   FIXED: {fixed}\n")
    results.append({
        "model": r["model"], "position": r["position"], "source_id": rec.get("id"),
        "original_sentence": r["sentence"], "corrected_sentence": fixed,
    })

save_mitigated(OUT_PATH, results)

"""
Mitigation = BASIC RAG.   Corrector model is switchable (Mistral or Falcon).

For every hallucinated sentence in hall_sent_clean.csv:
  1. resolve its source judgment in test.json (via labelled source_id),
  2. retrieve the top-k most relevant evidence sentences from that judgment,
  3. ask the corrector LLM to rewrite the sentence so it is faithful to evidence.
Output: outputs/basic_rag_<engine>_mitigated.csv  (original vs corrected).

>>> Pick the corrector model by editing MODEL_ENGINE below. <<<
"""

import numpy as np
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
from sentence_transformers import SentenceTransformer

# ─── INLINE HELPERS (this file is self-contained, no hall_utils.py needed) ───
import os, re, csv, json

_MODELS    = r'MISTRAL-7B|FALCON-7B'
_HALL_PAT  = re.compile(rf'^({_MODELS})(first|middle|last)(.+)$')
_STOPWORDS = {"the","and","that","this","with","from","were","have","has","had","was",
              "are","for","not","but","which","their","they","them","his","her","she",
              "him","who","whom","been","into","under","upon","such","shall","would",
              "could","there","these","those","than","then","also"}

def _load_hall_csv(path):
    rows = []
    with open(path, "r", encoding="utf-8-sig", newline="") as f:
        for row in csv.DictReader(f):
            sent = (row.get("sentence") or "").strip()
            if not sent:
                continue
            sid = (row.get("source_id") or "").strip()
            rows.append({"model": (row.get("model") or "").strip(),
                         "position": (row.get("position") or "").strip(),
                         "sentence": sent,
                         "source_id": sid if sid != "" else None,
                         "score": (row.get("score") or "").strip()})
    return rows

def load_hall_sentences(path):
    """Load hallucinated sentences. .csv -> labelled rows (with source_id);
    .txt -> legacy glued '<MODEL><position><sentence>' dump (source_id=None)."""
    if not os.path.exists(path):
        raise FileNotFoundError(f"{path} not found")
    if path.lower().endswith(".csv"):
        return _load_hall_csv(path)
    rows = []
    with open(path, "r", encoding="utf-8", errors="ignore") as f:
        for line in f:
            m = _HALL_PAT.match(line.strip())
            if m:
                rows.append({"model": m.group(1), "position": m.group(2),
                             "sentence": m.group(3).strip(), "source_id": None, "score": ""})
    return rows

def load_source_records(path):
    """Load the source judgments (the truth)."""
    if not os.path.exists(path):
        raise FileNotFoundError(f"{path} not found")
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    return data if isinstance(data, list) else [data]

def split_sentences(text):
    text = " ".join(str(text).split())
    parts = re.split(r'(?<=[.!?])\s+', text)
    return [s.strip() for s in parts if len(s.strip()) > 15]

def _keywords(text):
    return {w for w in re.findall(r'[A-Za-z]{4,}', text.lower()) if w not in _STOPWORDS}

def match_record(sentence, records):
    """Infer the source judgment by keyword overlap (fallback when no source_id)."""
    sw = _keywords(sentence)
    best_score, best_rec = -1, records[0]
    for rec in records:
        hay = (str(rec.get("judgment","")) + " " + str(rec.get("reference_summary",""))).lower()
        score = sum(1 for w in sw if w in hay)
        if score > best_score:
            best_score, best_rec = score, rec
    return best_rec

def pick_record(row, records):
    """Use the labelled source_id (exact lookup); else fall back to inference."""
    sid = row.get("source_id")
    if sid not in (None, ""):
        sid_str = str(sid).strip()
        for rec in records:
            if str(rec.get("id")).strip() == sid_str:
                return rec
        print(f"[WARN] source_id {sid_str!r} not found in test.json - inferring instead.")
    return match_record(row["sentence"], records)

def save_corrected(out_path, rows, extra_cols=None):
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    cols = ["model","position","source_id","original_sentence","corrected_sentence"] + list(extra_cols or [])
    with open(out_path, "w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=cols, extrasaction="ignore")
        w.writeheader()
        for r in rows:
            w.writerow(r)
    print(f"[SAVE] Wrote {len(rows)} corrected sentences -> {out_path}")
def save_mitigated(out_path, rows):
    """Write ONLY the mitigated sentences in the SAME schema as hall_sent_clean.csv
    (source_id, model, position, score, sentence) so this file can be re-fed to the
    detection methods and compared against the original input. score is left blank."""
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    with open(out_path, "w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=["source_id","model","position","sentence"])
        w.writeheader()
        for r in rows:
            w.writerow({"source_id": r.get("source_id",""),
                        "model":     r.get("model",""),
                        "position":  r.get("position",""),
                        "sentence":  r.get("corrected_sentence","")})
    print(f"[SAVE] Wrote {len(rows)} mitigated sentences -> {out_path}")
# ─── END INLINE HELPERS ─────────────────────────────────────────────────────

# ─── PICK YOUR CORRECTOR MODEL ──────────────────────────────────────────────
MODEL_ENGINE = "falcon"          # "mistral"  or  "falcon"

MODEL_IDS = {
    #"mistral": "mistralai/Mistral-7B-Instruct-v0.2",
    "falcon":  "tiiuae/falcon-7b-instruct",
}
assert MODEL_ENGINE in MODEL_IDS, f"MODEL_ENGINE must be one of {list(MODEL_IDS)}"
MODEL_ID = MODEL_IDS[MODEL_ENGINE]

# ─── CONFIGURATION ──────────────────────────────────────────────────────────
EMBED_MODEL = "all-MiniLM-L6-v2"
HALL_PATH   = "/content/hall_sent_clean.csv"
SRC_PATH    = "/content/test.json"
OUT_PATH    = f"outputs/basic_rag_{MODEL_ENGINE}_mitigated.csv"
TOP_K       = 3 if MODEL_ENGINE == "mistral" else 2     # Falcon has a 2048 window
MAX_CTX     = 4096 if MODEL_ENGINE == "mistral" else 2048
GEN_TEMP    = 0.1 if MODEL_ENGINE == "mistral" else 0.2
DEVICE      = "cuda" if torch.cuda.is_available() else "cpu"

INSTRUCTION = ("You are correcting a sentence from a legal-case summary so it is faithful "
               "to the source judgment. Use ONLY the context below. Rewrite the sentence to "
               "be factually accurate; drop or fix any claim not supported by the context. "
               "Reply with the corrected sentence only.")

def build_prompt(context, sentence):
    """Engine-specific instruction wrapper."""
    if MODEL_ENGINE == "mistral":
        return f"<s>[INST] {INSTRUCTION}\n\nContext:\n{context}\n\nSentence to correct: {sentence} [/INST]"
    return (f"{INSTRUCTION}\n\nContext:\n{context}\n\n"
            f"Sentence to correct: {sentence}\n\nCorrected sentence:")

# ─── 1. LOAD TARGETS (hallucinated) + TRUTH (source judgments) ──────────────
print(f"[1/4] Engine={MODEL_ENGINE} | loading {HALL_PATH} and {SRC_PATH} ...")
hall_rows = load_hall_sentences(HALL_PATH)
records   = load_source_records(SRC_PATH)
print(f"      {len(hall_rows)} hallucinated sentences | {len(records)} source judgments")

# ─── 2. EMBEDDER + EVIDENCE RETRIEVAL ───────────────────────────────────────
print("[2/4] Loading embedder ...")
embedder = SentenceTransformer(EMBED_MODEL, device=DEVICE)
_pool_cache = {}

def retrieve_evidence(query, record, k=TOP_K):
    sid = record.get("id")
    if sid not in _pool_cache:
        pool = split_sentences(record.get("judgment", "")) or [record.get("judgment", "")]
        emb  = embedder.encode(pool, convert_to_numpy=True, normalize_embeddings=True)
        _pool_cache[sid] = (pool, emb)
    pool, emb = _pool_cache[sid]
    q = embedder.encode([query], convert_to_numpy=True, normalize_embeddings=True)[0]
    idx = (emb @ q).argsort()[::-1][:k]
    return [pool[i] for i in idx]

# ─── 3. LOAD CORRECTOR LLM ──────────────────────────────────────────────────
print(f"[3/4] Loading {MODEL_ID} on {DEVICE} ...")
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
tokenizer.pad_token = tokenizer.eos_token
model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    torch_dtype=torch.float16 if DEVICE == "cuda" else torch.float32,
    device_map="auto" if DEVICE == "cuda" else None,
    low_cpu_mem_usage=True,
)

def correct_sentence(bad_sentence, evidence):
    context = "\n".join(f"- {e}" for e in evidence)
    prompt  = build_prompt(context, bad_sentence)
    inputs  = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=MAX_CTX).to(model.device)
    with torch.no_grad():
        out = model.generate(**inputs, max_new_tokens=120, do_sample=True, temperature=GEN_TEMP,
                             top_p=0.9, pad_token_id=tokenizer.eos_token_id)
    text = tokenizer.decode(out[0][inputs["input_ids"].shape[1]:], skip_special_tokens=True)
    return text.strip().strip('"')

# ─── 4. CORRECT EACH HALLUCINATED SENTENCE ──────────────────────────────────
print("[4/4] Correcting sentences ...\n")
results = []
for i, r in enumerate(hall_rows, 1):
    rec      = pick_record(r, records)
    evidence = retrieve_evidence(r["sentence"], rec, k=TOP_K)
    fixed    = correct_sentence(r["sentence"], evidence)
    print(f"[{i}/{len(hall_rows)}] {r['model']}/{r['position']}  (source id {rec.get('id')})")
    print(f"   ORIG : {r['sentence']}")
    print(f"   FIXED: {fixed}\n")
    results.append({
        "model": r["model"], "position": r["position"], "source_id": rec.get("id"),
        "original_sentence": r["sentence"], "corrected_sentence": fixed,
    })

save_mitigated(OUT_PATH, results)

