# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15somJneuKNCSR2YG-oOKNcDwwmS_1X7c
"""

"""
role_part.py
Mitigation = POSITIONAL ROLE PARTITIONING with ORDERED CONSTRAINT FORCING.
Runs BOTH Mistral and Falcon automatically, one after the other.

Core logic — hallucination severity: first < middle < last
Correction constraint is INVERSELY ordered (stricter where hallucination is worse):

    Position   temp    top_k   NLI check   threshold   retries   fallback
    ────────   ─────   ─────   ─────────   ─────────   ───────   ────────
    first      0.3     2       No          —           0         No
    middle     0.2     3       Yes         0.40        2         No
    last       0.1     4       Yes         0.50        3         Yes

Position label comes directly from hall_sent_clean.csv (hall_utils).
No judgment splitting is done — position is already known from the CSV.

Outputs:
    outputs/role_part_mistral_mitigated.csv
    outputs/role_part_falcon_mitigated.csv
"""

import os
import gc
import re
import csv
import json
import torch
import pandas as pd
from transformers import AutoTokenizer, AutoModelForCausalLM
from sentence_transformers import SentenceTransformer, CrossEncoder

# ─── INLINE HELPERS ──────────────────────────────────────────────────────────
_MODELS   = r'BART|LED|PEGASUS|MISTRAL-7B|FALCON-7B'
_HALL_PAT = re.compile(rf'^({_MODELS})(first|middle|last)(.+)$')
_STOPWORDS = {"the","and","that","this","with","from","were","have","has","had","was",
              "are","for","not","but","which","their","they","them","his","her","she",
              "him","who","whom","been","into","under","upon","such","shall","would",
              "could","there","these","those","than","then","also"}

def _load_hall_csv(path):
    rows = []
    with open(path, "r", encoding="utf-8-sig", newline="") as f:
        for row in csv.DictReader(f):
            sent = (row.get("sentence") or "").strip()
            if not sent:
                continue
            sid = (row.get("source_id") or "").strip()
            rows.append({"model":    (row.get("model")    or "").strip(),
                         "position": (row.get("position") or "").strip(),
                         "sentence": sent,
                         "source_id": sid if sid != "" else None,
                         "score":    (row.get("score")    or "").strip()})
    return rows

def load_hall_sentences(path):
    if not os.path.exists(path):
        raise FileNotFoundError(f"{path} not found")
    if path.lower().endswith(".csv"):
        return _load_hall_csv(path)
    rows = []
    with open(path, "r", encoding="utf-8", errors="ignore") as f:
        for line in f:
            m = _HALL_PAT.match(line.strip())
            if m:
                rows.append({"model": m.group(1), "position": m.group(2),
                             "sentence": m.group(3).strip(),
                             "source_id": None, "score": ""})
    return rows

def load_source_records(path):
    if not os.path.exists(path):
        raise FileNotFoundError(f"{path} not found")
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    return data if isinstance(data, list) else [data]

def split_sentences(text):
    text = " ".join(str(text).split())
    parts = re.split(r'(?<=[.!?])\s+', text)
    return [s.strip() for s in parts if len(s.strip()) > 15]

def _keywords(text):
    return {w for w in re.findall(r'[A-Za-z]{4,}', text.lower())
            if w not in _STOPWORDS}

def match_record(sentence, records):
    sw = _keywords(sentence)
    best_score, best_rec = -1, records[0]
    for rec in records:
        hay = (str(rec.get("judgment","")) + " " +
               str(rec.get("reference_summary",""))).lower()
        score = sum(1 for w in sw if w in hay)
        if score > best_score:
            best_score, best_rec = score, rec
    return best_rec

def pick_record(row, records):
    sid = row.get("source_id")
    if sid not in (None, ""):
        sid_str = str(sid).strip()
        for rec in records:
            if str(rec.get("id")).strip() == sid_str:
                return rec
        print(f"[WARN] source_id {sid_str!r} not found — inferring instead.")
    return match_record(row["sentence"], records)

def save_mitigated(out_path, rows):
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    fieldnames = ["source_id","model","position","original_sentence",
                  "corrected_sentence","constraint_temp","constraint_topk",
                  "nli_check","original_score","corrected_score",
                  "retries","outcome","is_mitigated"]
    with open(out_path, "w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        w.writeheader()
        for r in rows:
            w.writerow(r)
    print(f"[SAVE] Wrote {len(rows)} rows → {out_path}")

# ─── FIXED CONFIGURATION ─────────────────────────────────────────────────────
EMBED_MODEL = "all-MiniLM-L6-v2"
NLI_MODEL   = "cross-encoder/nli-deberta-v3-small"
HALL_PATH   = "/content/hall_sent_clean.csv"
SRC_PATH    = "/content/test.json"
DEVICE      = "cuda" if torch.cuda.is_available() else "cpu"

# ─── PER-ENGINE CONFIGURATION ────────────────────────────────────────────────
ENGINE_CONFIG = {
    "mistral": {
        "model_id": "mistralai/Mistral-7B-Instruct-v0.2",
        "max_ctx":  4096,
        "out_path": "outputs/role_part_mistral_mitigated.csv",
    },
    "falcon": {
        "model_id": "tiiuae/falcon-7b-instruct",
        "max_ctx":  2048,
        "out_path": "outputs/role_part_falcon_mitigated.csv",
    },
}

# ─── POSITIONAL CONSTRAINT TABLE ─────────────────────────────────────────────
# position label comes directly from hall_sent_clean.csv — no judgment splitting
# first < middle < last in hallucination severity
# → first > middle > last in temperature (lower temp = stricter)
POSITION_CONFIG = {
    "first": {
        "top_k":        2,      # fewest evidence chunks
        "temperature":  0.3,    # highest temp — lightest fix
        "nli_check":    False,  # no verification needed
        "nli_threshold":None,
        "max_retries":  0,
        "fallback":     False,
    },
    "middle": {
        "top_k":        3,
        "temperature":  0.2,
        "nli_check":    True,
        "nli_threshold":0.40,
        "max_retries":  2,
        "fallback":     False,
    },
    "last": {
        "top_k":        4,      # most evidence chunks
        "temperature":  0.1,    # lowest temp — strictest fix
        "nli_check":    True,
        "nli_threshold":0.50,
        "max_retries":  3,
        "fallback":     True,   # only last gets fallback
    },
}

# ─── LOAD SHARED DATA + MODELS ONCE ──────────────────────────────────────────
os.makedirs("outputs", exist_ok=True)

if not os.path.exists(HALL_PATH):
    raise FileNotFoundError(f"{HALL_PATH} not found.")
if not os.path.exists(SRC_PATH):
    raise FileNotFoundError(f"{SRC_PATH} not found.")

print(f"[INIT] Loading data ...")
hall_rows = load_hall_sentences(HALL_PATH)
records   = load_source_records(SRC_PATH)
print(f"       {len(hall_rows)} hallucinated sentences | {len(records)} source judgments")
print(f"       position labels from CSV — no judgment splitting")

print(f"[INIT] Loading embedder + NLI on {DEVICE} ...")
embedder = SentenceTransformer(EMBED_MODEL, device=DEVICE)
nli      = CrossEncoder(NLI_MODEL, device=DEVICE)
# DeBERTa label order: [contradiction=0, entailment=1, neutral=2]

# ─── EVIDENCE CACHE ───────────────────────────────────────────────────────────
_pool_cache = {}

def retrieve_evidence(query, record, k):
    """Retrieve top-k sentences from the FULL source judgment."""
    sid = record.get("id")
    if sid not in _pool_cache:
        pool = split_sentences(record.get("judgment","")) or [record.get("judgment","")]
        emb  = embedder.encode(pool, convert_to_numpy=True, normalize_embeddings=True)
        _pool_cache[sid] = (pool, emb)
    pool, emb = _pool_cache[sid]
    q   = embedder.encode([query], convert_to_numpy=True, normalize_embeddings=True)[0]
    idx = (emb @ q).argsort()[::-1][:k]
    return [pool[i] for i in idx]

def nli_entailment(premise, hypothesis):
    scores = nli.predict([(premise, hypothesis)], apply_softmax=True)
    return round(float(scores[0][1]), 4)

# ─── MAIN: LOOP OVER BOTH ENGINES ────────────────────────────────────────────
for ENGINE in ["mistral", "falcon"]:

    cfg      = ENGINE_CONFIG[ENGINE]
    MODEL_ID = cfg["model_id"]
    MAX_CTX  = cfg["max_ctx"]
    OUT_PATH = cfg["out_path"]

    print(f"\n{'='*70}")
    print(f"  ENGINE : {ENGINE.upper()}  →  {MODEL_ID}")
    print(f"  max_ctx: {MAX_CTX}  |  device: {DEVICE}")
    print(f"{'='*70}\n")

    # ── prompt builder — engine-specific format ───────────────────────────
    def build_prompt(position, context, sentence):
        POSITION_INSTRUCTION = {
            "first": (
                "You are correcting the OPENING sentence of a legal-case summary. "
                "Lightly rewrite it to remove any unsupported claims. "
                "Use ONLY the context provided."
            ),
            "middle": (
                "You are correcting a MIDDLE sentence of a legal-case summary. "
                "Middle sentences often contain fabricated dates, section numbers, "
                "or party names. Rewrite strictly using ONLY the context. "
                "Drop or fix every claim not found in the context."
            ),
            "last": (
                "You are correcting the FINAL sentence of a legal-case summary. "
                "Final sentences have the highest hallucination — they often invent "
                "conclusions. Be extremely strict: use ONLY what is explicitly in "
                "the context. Remove any claim that cannot be verified. "
                "Reply with one corrected sentence only."
            ),
        }
        instruction = POSITION_INSTRUCTION[position]
        if ENGINE == "mistral":
            return (f"<s>[INST] {instruction}\n\n"
                    f"Context:\n{context}\n\n"
                    f"Sentence: {sentence} [/INST]")
        return (f"{instruction}\n\n"
                f"Context:\n{context}\n\n"
                f"Sentence: {sentence}\n\n"
                f"Corrected sentence:")

    # ── load LLM ─────────────────────────────────────────────────────────
    print(f"  Loading {MODEL_ID} ...")
    tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
    tokenizer.pad_token = tokenizer.eos_token
    llm = AutoModelForCausalLM.from_pretrained(
        MODEL_ID,
        torch_dtype=torch.float16 if DEVICE == "cuda" else torch.float32,
        device_map="auto" if DEVICE == "cuda" else None,
        low_cpu_mem_usage=True,
    )
    llm.eval()

    # ── generation ───────────────────────────────────────────────────────
    def generate_once(position, context_str, sentence, temperature):
        prompt = build_prompt(position, context_str, sentence)
        inputs = tokenizer(
            prompt, return_tensors="pt",
            truncation=True, max_length=MAX_CTX
        ).to(llm.device)
        with torch.no_grad():
            out = llm.generate(
                **inputs,
                max_new_tokens=120,
                do_sample=True,
                temperature=temperature,
                top_p=0.9,
                repetition_penalty=1.15,
                use_cache=True,
                pad_token_id=tokenizer.eos_token_id,
            )
        raw = tokenizer.decode(
            out[0][inputs["input_ids"].shape[1]:],
            skip_special_tokens=True
        ).strip().strip('"')
        for prefix in ["Corrected sentence:", "Corrected:", "Answer:"]:
            if raw.lower().startswith(prefix.lower()):
                raw = raw[len(prefix):].strip()
        parts = [s.strip() for s in raw.split(".") if s.strip()]
        return (parts[0] + ".") if parts else raw

    # ── positional constraint correction ─────────────────────────────────
    def correct_with_constraint(position, sentence, evidence):
        cfg_p        = POSITION_CONFIG[position]
        temperature  = cfg_p["temperature"]
        nli_check    = cfg_p["nli_check"]
        threshold    = cfg_p["nli_threshold"]
        max_retries  = cfg_p["max_retries"]
        use_fallback = cfg_p["fallback"]
        context_str  = "\n".join(f"- {e}" for e in evidence)
        premise      = " ".join(evidence)

        # first — single pass, no NLI check
        if not nli_check:
            fixed = generate_once(position, context_str, sentence, temperature)
            score = nli_entailment(premise, fixed)
            return fixed, score, 0, "no_check"

        # middle / last — generate + verify
        fixed = generate_once(position, context_str, sentence, temperature)
        score = nli_entailment(premise, fixed)
        if score >= threshold:
            return fixed, score, 0, "passed_first_try"

        # retry loop — lower temp each attempt
        for attempt in range(1, max_retries + 1):
            retry_temp = max(temperature - 0.05 * attempt, 0.05)
            fixed      = generate_once(position, context_str, sentence, retry_temp)
            score      = nli_entailment(premise, fixed)
            if score >= threshold:
                return fixed, score, attempt, f"passed_retry_{attempt}"

        # fallback — last position only
        if use_fallback:
            fallback = "This claim could not be verified against the source judgment."
            fb_score = nli_entailment(premise, fallback)
            return fallback, fb_score, max_retries, "fallback"

        # middle — return best attempt even if below threshold
        return fixed, score, max_retries, "below_threshold_accepted"

    # ── correction loop ───────────────────────────────────────────────────
    print(f"  Running correction loop ...")
    print(f"  first  → temp=0.3 top_k=2 no NLI")
    print(f"  middle → temp=0.2 top_k=3 NLI≥0.40 retry×2")
    print(f"  last   → temp=0.1 top_k=4 NLI≥0.50 retry×3 fallback\n")

    results = []
    for i, r in enumerate(hall_rows, 1):
        position = r["position"]   # from CSV — no re-splitting
        sentence = r["sentence"]
        cfg_p    = POSITION_CONFIG[position]

        rec      = pick_record(r, records)
        evidence = retrieve_evidence(sentence, rec, k=cfg_p["top_k"])

        fixed, score, retries, outcome = correct_with_constraint(
            position, sentence, evidence
        )

        premise        = " ".join(evidence)
        original_score = nli_entailment(premise, sentence)
        is_mitigated   = (score > original_score and
                          score >= (cfg_p["nli_threshold"] or 0.0))

        flag = "✓ MITIGATED" if is_mitigated else "✗ WEAK"
        print(f"  [{i}/{len(hall_rows)}] {r['model']}/{position} "
              f"(src {rec.get('id')}) | {flag}")
        print(f"     temp={cfg_p['temperature']} top_k={cfg_p['top_k']} "
              f"orig={original_score} corr={score} retries={retries} {outcome}")
        print(f"     ORIG : {sentence}")
        print(f"     FIXED: {fixed}\n")

        results.append({
            "model":             r["model"],
            "position":          position,
            "source_id":         rec.get("id"),
            "original_sentence": sentence,
            "corrected_sentence":fixed,
            "constraint_temp":   cfg_p["temperature"],
            "constraint_topk":   cfg_p["top_k"],
            "nli_check":         cfg_p["nli_check"],
            "original_score":    original_score,
            "corrected_score":   score,
            "retries":           retries,
            "outcome":           outcome,
            "is_mitigated":      is_mitigated,
        })

    # ── summary ───────────────────────────────────────────────────────────
    df = pd.DataFrame(results)
    print(f"\n  Summary for {ENGINE.upper()}:")
    print(
        df.groupby("position")
        .agg(
            total=("is_mitigated","count"),
            mitigated=("is_mitigated", lambda x: int(x.sum())),
            avg_orig=("original_score","mean"),
            avg_corr=("corrected_score","mean"),
            avg_retries=("retries","mean"),
        )
        .reindex(["first","middle","last"])
        .round(4)
        .to_string()
    )

    save_mitigated(OUT_PATH, results)

    # ── free GPU before loading next engine ───────────────────────────────
    print(f"\n  Freeing {ENGINE.upper()} from GPU ...")
    del llm, tokenizer
    gc.collect()
    if DEVICE == "cuda":
        torch.cuda.empty_cache()

print("\n" + "="*70)
print("BOTH ENGINES DONE")
print("  outputs/role_part_mistral_mitigated.csv")
print("  outputs/role_part_falcon_mitigated.csv")
print("="*70)

